### ISSUE TITLE
Add some delay between moves (100ms - 800ms)

### ISSUE THREAD

**Issue by ishtiaqSamdani** [phanindra-max/xxx-hurray#10]
computer moves are so fast as flash(⚡)
it will be a good user experience if it took a little more time⏳

**Comment by BRC-Thomas** [comment]
Hi i've made a merge request, i added random delay between 100 to 800ms
![image](https://github.com/phanindra-max/noOX-AI/assets/123388670/e3a6359f-b3cd-45d3-bcf7-1d2196fde7cb)

**Comment by phanindra-max** [comment]
Great work, Thomas!⚡
