### ISSUE TITLE
Add an option for the player to play first or let computer play first

### ISSUE THREAD

**Issue by phanindra-max** [phanindra-max/xxx-hurray#6]
This is another simple feature to add to the game.

The users should be prompted if they want to play first or let the computer play first.

Reach out if you have any issues/doubts regarding the code.

**Comment by cod500** [comment]
Do you mind if I tackle this for you? I enjoy working on small issues with game interaction.

**Comment by phanindra-max** [comment]
Sorry for the late reply. 
You did a great job.
I merged your pull request.
Stay safe and keep rocking my friend 😉✌️
